disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
included:
  - HelloCustomer
  - Example
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
reporter: "xcode"
